//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{

    // Где лежит БД?Нужно добавить поле Role и пересобрать edmx file я ее только пофоксила боюсь что она опять полетит
    // а что было? ну помнишь первую ошибку то проблема с бд была я ее пересобрала
    // тогда на будущее те нужно поле Role
    // а пока у тебя есть хеш пароля в БД и ты его сравниваешь с паролем, который тоже хешируешь на входе
    // можешь пока просто проверять на соответствие Логина и Пароля
    // Потом ещё можно будет проверять по Ролям ну мне пока по лоогину и паролю ха\ватит
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    }
}
